apiVersion: v1
kind: Service
metadata:
  name: hazelcast
spec:
  ports:
  - protocol: "TCP"
    port: 5701
    targetPort: 5701
  type: LoadBalancer
  selector:
    app: hazelcast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: hazelcast/hazelcast:latest
        #resources:
        #  requests:
        #    memory: 2000Mi
        #    cpu: 1
        #  limits:
        #    memory: 2000Mi
        #    cpu: 1
        ports:
        - containerPort: 5701
