apiVersion: v1
kind: Service
metadata:
  name: treblemakerweb
spec:
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 
    nodePort: 30001
  selector:
    app: treblemakerweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treblemakerweb
  labels:
    app: treblemakerweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treblemakerweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: treblemakerweb
    spec:
      containers:
      - name: treblemakerweb
        image: stevehiehn/treblemakerweb:latest
        ports:
        - containerPort: 3000

