apiVersion: v1
kind: Service
metadata:
  name: treblemakercore
spec:
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 8888
  selector:
    app: treblemakercore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treblemakercore
  labels:
    app: treblemakercore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treblemakercore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: treblemakercore
    spec:
      containers:
      - name: treblemakercore
        image: stevehiehn/treblemakercore:0
        imagePullPolicy: Always
        env:
        - name: AWS_BUCKET_NAME
          value: "songseeds"
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""

