apiVersion: v1
kind: Service
metadata:
  name: treblemakerapi
spec:
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 7777
    targetPort:
    nodePort: 30000
  selector:
    app: treblemakerapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treblemakerapi
  labels:
    app: treblemakerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treblemakerapi
  template:
    metadata:
      labels:
        app: treblemakerapi
    spec:
      containers:
      - name: treblemakerapi
        image: stevehiehn/treblemakerapi:0
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
        env:
        - name: AWS_BUCKET_NAME
          value: "songseeds"
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
